# run: conda env create --file environment.yml
name: dronedetector
channels:
  - defaults
dependencies: 
  - pip
  - python=3.8.5
  - pytorch::cpuonly
  - fastchan::fastai
  - fastchan::nbdev
  - conda-forge::gdal=3.1.2
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::rtree
  - conda-forge::xarray
  - conda-forge::jupyter_contrib_nbextensions
  - pip:
    - opencv-python 
    - scikit-image 
    - albumentations
    - pyarrow
    - wandb
    - tensorboard
    - captum
    - laspy
    - xlrd
    - jedi==0.17.2
    - icevision[all]
    - gradio
    - torchsummary
