name: 'build-docs'
description: 'create docs'
inputs:
  ghtoken:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: test
        use-mamba: true

    - name: Install environment
      run: mamba env update -n test -f ci/test_environment.yml
      shell: bash -l {0}

    - name: make docs
      shell: bash -l {0}
      run: nbdev_docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.ghtoken }}
        force_orphan: true
        publish_dir: ./_docs
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
