# run: conda env create --file environment.yml
name: test
channels:
  - defaults
  - fastchan
  - conda-forge
dependencies: 
  - pip
  - pytorch::cpuonly
  - fastchan::fastai==2.5.3
  - fastchan::nbdev
  - conda-forge::gdal=3.1.2
  - conda-forge::geopandas
  - conda-forge::rasterio
  - defaults::xarray
  - pip:
    - opencv-python 
    - scikit-image 
    - albumentations
    - pyarrow
    - wandb
    - tensorboard
    - captum
    - laspy
    - xlrd
    - git+https://github.com/airctic/icevision.git#egg=icevision[all]
    - ipywidgets
    - detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html
    - ensemble-boxes
    - seaborn
