name: testenv
channels:
  - conda-forge
  - fastchan
  - pytorch
dependencies: 
  - conda-forge::pip
  - fastchan::fastai==2.7.12
  - pytorch::pytorch==2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - fastchan::nbdev
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::jupyter_contrib_nbextensions
  - pip:
    - opencv-python 
    - scikit-image 
    - pyarrow
    - wandb
    - tensorboard
    - captum
    - laspy
    - seaborn
    - torchsummary
    - albumentations
    - "git+https://github.com/waspinator/pycococreator.git@0.2.0"
    - "git+https://github.com/facebookresearch/detectron2.git"

