# run: conda env create --file environment.yml
name: test
channels:
  - defaults
  - fastchan
  - conda-forge
dependencies: 
  - pip
  - python=3.8.5
  - pytorch::cpuonly
  - fastchan::fastai==2.3.1
  - fastchan::pillow=8.2.0
  - fastchan::nbdev
  - conda-forge::gdal=3.1.2
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::rtree
  - conda-forge::xarray
  - pip:
    - opencv-python 
    - scikit-image 
    - albumentations
    - pyarrow
    - wandb
    - tensorboard
    - captum
    - laspy
    - xlrd
    - jedi==0.17.2
    - icevision
    - ipywidgets
