# run: conda env create --file environment.yml
name: test
channels:
  - defaults
  - fastchan
  - conda-forge
dependencies: 
  - pip
  - pytorch::cpuonly
  - fastchan::fastai==2.5.3
  - fastchan::nbdev
  - conda-forge::gdal
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::jupyter_contrib_nbextensions
  - bokeh
  - pyviz::holoviews
  - pyviz::hvplot
  - defaults::xarray
  - pip:
    - opencv-python 
    - scikit-image 
    - pyarrow
    - wandb
    - tensorboard
    - captum
    - laspy
    - git+https://github.com/airctic/icevision.git#egg=icevision[all]
    - seaborn
    - torchsummary
