name: test
channels:
  - conda-forge
  - fastchan
  - pytorch
dependencies: 
  - conda-forge::python==3.9
  - conda-forge::pip
  - pytorch::cpuonly
  - pytorch::pytorch==1.10
  - fastchan::fastai==2.7.7
  - fastchan::nbdev
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::jupyter_contrib_nbextensions
  - pip:
    - opencv-python 
    - scikit-image 
    - pyarrow
    - wandb
    - tensorboard
    - captum
    - laspy
    - seaborn
    - torchsummary
    - albumentations
